//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoLimpio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprendimientos4RI
    {
        public int IdEmprendimientos4RI { get; set; }
        public int IdHerramientas4RI { get; set; }
        public int IdEmprendimientos { get; set; }
    
        public virtual Emprendimientos Emprendimientos { get; set; }
        public virtual Herramientas4RI Herramientas4RI { get; set; }
    }
}
