//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoLimpio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprendimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emprendimientos()
        {
            this.EmprendimientoEmpleado = new HashSet<EmprendimientoEmpleado>();
            this.IdeasConjunto = new HashSet<IdeasConjunto>();
            this.Emprendimientos4RI = new HashSet<Emprendimientos4RI>();
            this.ImpactoEmprendimiento = new HashSet<ImpactoEmprendimiento>();
        }
    
        public int IdEmprendimientos { get; set; }
        public string NombreEmprendimiento { get; set; }
        public int InversionRequerida { get; set; }
        public int IngresosProyectados { get; set; }
        public int InversionInfraestructura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmprendimientoEmpleado> EmprendimientoEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeasConjunto> IdeasConjunto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprendimientos4RI> Emprendimientos4RI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpactoEmprendimiento> ImpactoEmprendimiento { get; set; }
    }
}
