//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoLimpio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impactos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Impactos()
        {
            this.ImpactoDepartamento1 = new HashSet<ImpactoDepartamento>();
            this.ImpactoEmprendimiento = new HashSet<ImpactoEmprendimiento>();
        }
    
        public int IdImpactos { get; set; }
        public string NombreImpacto { get; set; }
        public string ImpactoDepartamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpactoDepartamento> ImpactoDepartamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpactoEmprendimiento> ImpactoEmprendimiento { get; set; }
    }
}
