//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodigoLimpio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactoEmprendimiento
    {
        public int IdImpactoEmprendimiento { get; set; }
        public int IdImpacto { get; set; }
        public int IdEmprendimiento { get; set; }
    
        public virtual Emprendimientos Emprendimientos { get; set; }
        public virtual Impactos Impactos { get; set; }
    }
}
